const lightTheme =  {
    // FONTS
    FONT_SIZE_LARGE: 16,
    FONT_SIZE_MEDIUM: 14,
    FONT_SIZE_SMALL: 12,

    FONT_WEIGHT_LIGHT: 200,
    FONT_WEIGHT_MEDIUM: 600,
    FONT_WEIGHT_HEAVY: 800,
    //COLORS
    FONT_COLOR_PRIMARY: '#333333',
    FONT_COLOR_SECONDARY: '#666666',
    FONT_COLOR_TERTIARY: '#999999',
    FONT_COLOR_QUATERNARY: '#ffffff',
    BACKGROUND_COLOR_PRIMARY: '#ffffff',
    
}

const darkTheme = {
    // FONTS
    FONT_SIZE_LARGE: 16,
    FONT_SIZE_MEDIUM: 14,
    FONT_SIZE_SMALL: 12,

    FONT_WEIGHT_LIGHT: 200,
    FONT_WEIGHT_MEDIUM: 600,
    FONT_WEIGHT_HEAVY: 800,
    // COLORS
    FONT_COLOR_PRIMARY: '#ffffff',
    FONT_COLOR_SECONDARY: '#cccccc',
    FONT_COLOR_TERTIARY: '#cccccc',
    FONT_COLOR_QUATERNARY: '#333333',
    BACKGROUND_COLOR_PRIMARY: '#333333',
}