export default {
    // FONTS
    FONT_SIZE_EXTRA_LARGE: 33,
    FONT_SIZE_LARGE: 25,
    FONT_SIZE_MEDIUM: 20,
    FONT_SIZE_SMALL: 16,

    FONT_WEIGHT_LIGHT: 200,
    FONT_WEIGHT_MEDIUM: 600,
    FONT_WEIGHT_HEAVY: 800,
    // COLORS
    FONT_COLOR_PRIMARY: '#000000',
    FONT_COLOR_SECONDARY: '#cccccc',
    FONT_COLOR_TERTIARY: '#cccccc',
    FONT_COLOR_QUATERNARY: '#333333',
    BACKGROUND_COLOR_PRIMARY: '#D9D9D9',
    POSITIVE_NUMBER_COLOR: "#17B439",
    NEGATIVE_NUMBER_COLOR: "#E1200F",

    // MARGINS
    SCREEN_TOP_MARGIN: 50,
    SCREEN_BOTTOM_MARGIN: 20,
    SCREEN_HORIZONTAL_MARGIN: 80,
    
}